version: '3.8'

services:
  db:
    container_name: pg_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clickcollect
    ports:
      - '5423:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data/
volumes:
  pg_data:
